version: '3.9'

services:
  postgres:
    image: postgres:13.2
    container_name: todo_api_postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - busy_db:/var/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 2s
      retries: 4
    networks:
      - custom_network

volumes:
  busy_db:

networks:
  custom_network: